tuconciergeweb/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using RestSharp;
using tuconciergemodels;
using tuconciergeweb.Interfaces;

namespace tuconciergeweb.Controllers
{
    public class CountriesController : BaseController, IViewController<Country>
    {
        private readonly string EndPoint = "/api/Countries";

        // CONSTRUCTOR
        public CountriesController() : base() { }


        // GET: Countries
        public ActionResult Index()
        {
            if (!SessionActive())
            {
                return Redirect("/Home/Login");
            }

            return View();
        }

        public ActionResult List()
        {
            Enums.ModelStatus status = Enums.ModelStatus.Active;
            if (Request.QueryString["Status"] != null)
            {
                status = (Enums.ModelStatus)int.Parse(Request.QueryString["Status"].ToString());
            }

            SetParameter(new Parameter("Status", status, ParameterType.QueryString));

            if (Request.QueryString["Name"] != null)
            {
                var name = Request.QueryString["Name"].ToString();

                SetParameter(new Parameter("Name", name, ParameterType.QueryString));
            }

            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<IEnumerable<Country>>(response.Content);

            return PartialView(model);
        }

        // GET: Countries/Form/5
        public ActionResult Form(long id = 0)
        {
            if(id == 0)
            {
                ViewBag.ModalTitle = "Agregar país";
                return PartialView(new Country());
            }

            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<Country>(response.Content);

            ViewBag.ModalTitle = "Editar país";
            return PartialView(model);
        }

        // POST: Countries/Create
        [HttpPost]
        public JsonResult Save(Country country)
        {
            try
            {
                if(country.Id != 0)
                {
                    SetParameter(new Parameter("id", country.Id, ParameterType.UrlSegment));

                    SetBody(country);

                    var response = SendRequest(Method.PUT, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);

                }
                else
                {
                    SetBody(country);

                    var response = SendRequest(Method.POST, EndPoint, Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);
                }
            }
            catch(Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }


        
        // GET: Countries/Delete/5
        public ActionResult ConfirmDelete(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<Country>(response.Content);

            return PartialView(model);
        }

        // POST: Countries/Delete/5
        [HttpPost]
        public JsonResult Delete(long id)
        {
            try
            {
                SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

                var response = SendRequest(Method.DELETE, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                return ValidateResponse(response);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Countries/Details/5
        public ActionResult Details(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<Country>(response.Content);

            return PartialView(model);
        }

        // GET: Countries/Select
        public ActionResult Select()
        {
            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<List<Country>>(response.Content);

            return PartialView(model);
        }
    }
}

tuconciergeweb/Controllers/OfficesController.cs
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tuconciergemodels;
using tuconciergeweb.Interfaces;
using tuconciergeweb.Services;

namespace tuconciergeweb.Controllers
{
    public class OfficesController : BaseController
    {
        private readonly string EndPoint = "/api/Offices";

        // CONSTRUCTOR
        public OfficesController() : base() { }

        public ActionResult ConfirmDelete(long id)
        {
            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<OfficeViewModel>(response.Content);

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            try
            {
                SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

                var response = SendRequest(Method.DELETE, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                return ValidateResponse(response);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Details(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<OfficeViewModel>(response.Content);

            return PartialView(model);
        }

        public ActionResult Location(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<OfficeViewModel>(response.Content);

            ViewBag.ModalTitle = "Establecer ubicación";
            ViewBag.SaveTextButton = "Guardar";
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult SaveLocation(Office model)
        {
            SetParameter(new Parameter("id", model.Id, ParameterType.UrlSegment));

            SetBody(model);

            var response = SendRequest(Method.PUT, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            return ValidateResponse(response);
        }

        public ActionResult Form(long id = 0)
        {
            if (id == 0)
            {
                ViewBag.ModalTitle = "Agregar sucursal";
                ViewBag.SaveTextButton = "Guardar";
                return PartialView(new OfficeViewModel());
            }

            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<OfficeViewModel>(response.Content);

            ViewBag.ModalTitle = "Editar sucursal";
            ViewBag.SaveTextButton = "Actualizar";
            return PartialView(model);
        }


        // GET: Countries
        public ActionResult Index()
        {
            if (!SessionActive())
            {
                return Redirect("/Home/Login");
            }

            return View();
        }

        public ActionResult List()
        {
            if (Request.QueryString["Name"] != null)
            {
                var name = Request.QueryString["Name"].ToString();

                SetParameter(new Parameter("Name", name, ParameterType.QueryString));
            }

            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<IEnumerable<OfficeViewModel>>(response.Content);

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Save(HttpPostedFileBase file, Office model)
        {
            try
            {
                if(file != null)
                {
                    var fileUpload = new FileUploadService();

                    model.Picture = fileUpload.ImageUpload(file);
                }

                if (model.Id != 0)
                {
                    SetParameter(new Parameter("id", model.Id, ParameterType.UrlSegment));

                    SetBody(model);

                    var response = SendRequest(Method.PUT, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);

                }
                else
                {
                    SetBody(model);

                    var response = SendRequest(Method.POST, EndPoint, Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Select()
        {
            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<List<Office>>(response.Content);

            return PartialView(model);
        }
    }
}

tuconciergeweb/Views/Offices/ConfirmDelete.cshtml
@model tuconciergemodels.OfficeViewModel

<div class="modal-header">
    <h5 class="modal-title" id="smModalLabel">¿Estás seguro que quieres eliminar esto?</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i class="ion ion-md-close-circle-outline"></i>
    </button>
</div>
<div class="modal-body" id="mdModalBody">

    <dl>

        <dt>
            Nombre fiscal
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

</div>
<div class="modal-footer">
    <button id="btnCancel" type="button" class="btn btn-danger btn-rounded btn-fw" data-dismiss="modal">Cancelar</button>
    <button id="btnDelete" type="button" class="btn btn-success btn-rounded btn-fw" onclick="Delete(@Model.Id);">Sí, eliminar</button>
</div>

tuconciergeweb/Views/Offices/Details.cshtml
@model tuconciergemodels.OfficeViewModel

@{
    Layout = null;
}


<div class="modal-header">
    <h5 class="modal-title" id="smModalLabel">Información de la empresa</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i class="ion ion-md-close-circle-outline"></i>
    </button>
</div>
<div class="modal-body" id="mdModalBody">

    <dl>
        <dt>
            Nombre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Dirección
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            Código Postal
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            Logo
        </dt>

        <dd>
            <img src="@Model.Picture" alt="image" class="img-sm mr-3 mt-1" style="width:auto !important; height:32px !important; border-radius: 0px !important;">
        </dd>

        <dt>
            Ciudad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

    </dl>

</div>

<div class="modal-footer">
    <button id="btnCancel" type="button" class="btn btn-dark btn-rounded btn-fw" data-dismiss="modal">Cancelar</button>
</div>

tuconciergeweb/Views/Offices/Form.cshtml
@model tuconciergemodels.OfficeViewModel

<div class="modal-header">
    <h5 class="modal-title">@ViewBag.ModalTitle</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i class="ion ion-md-close-circle-outline"></i>
    </button>
</div>
<div class="modal-body" id="mdModalBody">

    <form id="officeForm" enctype="multipart/form-data">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label for="Name">Nombre</label>
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nombre" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="files">Logo</label>
            <input id="files" type="file" name="file" accept="image/x-png,image/jpeg" class="form-control" , placeholder="Subir imagen">
        </div>

        <div class="form-group">
            <label for="Address">Dirección</label>
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @placeholder = "Dirección" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="PostalCode">Código postal</label>
            @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control", @placeholder = "Código Postal" } })
            @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="selectCountry">País</label>
            <select class="form-control" id="selectCountry" onchange="getStates(this);">
                <option value="0">Seleccionar...</option>
                @Html.Action("Select", "Countries")
            </select>
        </div>

        <div class="form-group">
            <label for="selectStates">Estados</label>
            <select disabled class="form-control" id="selectStates">
            </select>
        </div>

        <div class="form-group">
            <label for="City">Ciudad</label>
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ciudad" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>

        @Html.HiddenFor(model => model.Lat)
        @Html.HiddenFor(model => model.Long)
        @Html.HiddenFor(model => model.CountryId)
        @Html.HiddenFor(model => model.StateId)
        @Html.HiddenFor(model => model.Picture)
        @Html.HiddenFor(model => model.Id)

    </form>

</div>
<div class="modal-footer">
    <button id="btnCancel" type="button" class="btn btn-danger btn-rounded btn-fw" data-dismiss="modal">Cancelar</button>
    <button id="btnSave" type="button" class="btn btn-success btn-rounded btn-fw" onclick="Save();">@ViewBag.SaveTextButton</button>
</div>

tuconciergeweb/Views/Offices/Index.cshtml
@{
    ViewBag.Title = "Sucursales";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-lg-12 grid-margin stretch-card">

    <div class="card">

        <div class="card-body">

            <h4 class="card-title">
                Catálogo Sucursales
            </h4>

            <div class="row d-flex align-items-center justify-content-start">

                <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                    <div class="form-group">
                        <label for="NombreFilter">Nombre</label>
                        <input type="text" class="form-control" id="NombreFilter" placeholder="Nombre">
                    </div>
                </div>

                <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                    <button type="button" class="btn btn-dark btn-rounded btn-fw" onclick="getList();">Buscar</button>
                </div>

            </div>

            <div class="row">

                <div class="col-lg-12 d-flex justify-content-end">
                    <button type="button" class="btn btn-success btn-rounded btn-fw" onclick="Create();">Agregar</button>
                </div>

                <div class="col-lg-12">
                    <div class="table-responsive" id="MyTable">

                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

@section scripts {
    <script src="~/Scripts/Offices.js"></script>
}

tuconciergeweb/Views/Offices/List.cshtml
@model IEnumerable<tuconciergemodels.OfficeViewModel>


@{
    ViewBag.CountElements = 0;
}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>No.</th>
                <th>
                    Logo
                </th>
                <th>
                    Nombre
                </th>
                <th>
                    Ciudad
                </th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() > 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @(ViewBag.CountElements += 1)
                        </td>
                        <td>
                            <img src="@item.Picture" alt="image" class="img-sm mr-3" style="width:auto !important; height:24px !important; border-radius: 0px !important;">
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.City)
                        </td>
                        <td>
                            <button type="button" class="btn btn-info btn-rounded btn-icon mt-2" onclick="Location(@item.Id)">
                                <i class="mdi mdi-map-marker"></i>
                            </button> |
                            <button type="button" class="btn btn-info btn-rounded btn-icon mt-2" onclick="Details(@item.Id)">
                                <i class="ion ion-md-eye"></i>
                            </button> |
                            <button type="button" class="btn btn-warning btn-rounded btn-icon mt-2" onclick="Edit(@item.Id);">
                                <i class="ion ion-md-refresh"></i>
                            </button> |
                            <button type="button" class="btn btn-danger btn-rounded btn-icon mt-2" onclick="ConfirmDelete(@item.Id);">
                                <i class="ion ion-md-trash"></i>
                            </button>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="5" align="center">
                        <h5>Sin resultados</h5>
                    </td>
                </tr>
            }
        </tbody>
    </table>

tuconciergeweb/Views/Offices/Location.cshtml
@model tuconciergemodels.OfficeViewModel

<div class="modal-header">
    <h5 class="modal-title">@ViewBag.ModalTitle</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i class="ion ion-md-close-circle-outline"></i>
    </button>
</div>
<div class="modal-body" id="mdModalBody">

    <form id="locationForm">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label for="map-search">Buscar</label>
            <input id="map-search" class="form-control controls" type="text" placeholder="Buscar..." style="width: 70% !important;">
        </div>

        @*<input hidden id="latitude" type="text" class="latitude">
        <input hidden id="longitude" type="text" class="longitude">*@
        <input hidden id="city" type="text" class="reg-input-city" placeholder="City">

        <div id="map-canvas" style="width:100%; height: 350px !important;"></div>

        @Html.HiddenFor(model => model.Name)
        @Html.HiddenFor(model => model.Address)
        @Html.HiddenFor(model => model.PostalCode)
        @Html.HiddenFor(model => model.Picture)
        @Html.HiddenFor(model => model.City)
        @Html.HiddenFor(model => model.CompanyId)
        @Html.HiddenFor(model => model.StateId)
        @Html.HiddenFor(model => model.CountryId)
        @Html.HiddenFor(model => model.Lat, new { @class="latitude" })
        @Html.HiddenFor(model => model.Long, new { @class="longitude" })
        @Html.HiddenFor(model => model.Id)

    </form>

</div>
<div class="modal-footer">
    <button id="btnCancel" type="button" class="btn btn-danger btn-rounded btn-fw" data-dismiss="modal">Cancelar</button>
    <button id="btnSave" type="button" class="btn btn-success btn-rounded btn-fw" onclick="SaveLocation();">@ViewBag.SaveTextButton</button>
</div>

<script src="~/Content/js/javascript.js"></script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUtY_C0qwAWw1ZY4UX8R_oNiO8ptMqlas&libraries=places&callback=initialize"></script>

tuconciergeweb/Views/Offices/Select.cshtml
@model List<tuconciergemodels.Office>

@foreach (var item in Model)
{
    <option value="@item.Id">@item.Name</option>
}