tuconciergeweb/Controllers/OfficesController.cs
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tuconciergemodels;
using tuconciergeweb.Interfaces;
using tuconciergeweb.Services;

namespace tuconciergeweb.Controllers
{
    public class OfficesController : BaseController
    {
        private readonly string EndPoint = "/api/Offices";

        // CONSTRUCTOR
        public OfficesController() : base() { }

        public ActionResult ConfirmDelete(long id)
        {
            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<OfficeViewModel>(response.Content);

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            try
            {
                SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

                var response = SendRequest(Method.DELETE, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                return ValidateResponse(response);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Details(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<OfficeViewModel>(response.Content);

            return PartialView(model);
        }

        public ActionResult Location(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<OfficeViewModel>(response.Content);

            ViewBag.ModalTitle = "Establecer ubicación";
            ViewBag.SaveTextButton = "Guardar";
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult SaveLocation(Office model)
        {
            SetParameter(new Parameter("id", model.Id, ParameterType.UrlSegment));

            SetBody(model);

            var response = SendRequest(Method.PUT, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            return ValidateResponse(response);
        }

        public ActionResult Form(long id = 0)
        {
            if (id == 0)
            {
                ViewBag.ModalTitle = "Agregar sucursal";
                ViewBag.SaveTextButton = "Guardar";
                return PartialView(new OfficeViewModel());
            }

            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<OfficeViewModel>(response.Content);

            ViewBag.ModalTitle = "Editar sucursal";
            ViewBag.SaveTextButton = "Actualizar";
            return PartialView(model);
        }


        // GET: Countries
        public ActionResult Index()
        {
            if (!SessionActive())
            {
                return Redirect("/Home/Login");
            }

            return View();
        }

        public ActionResult List()
        {
            if (Request.QueryString["Name"] != null)
            {
                var name = Request.QueryString["Name"].ToString();

                SetParameter(new Parameter("Name", name, ParameterType.QueryString));
            }

            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<IEnumerable<OfficeViewModel>>(response.Content);

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Save(HttpPostedFileBase file, Office model)
        {
            try
            {
                if(file != null)
                {
                    var fileUpload = new FileUploadService();

                    model.Picture = fileUpload.ImageUpload(file);
                }

                if (model.Id != 0)
                {
                    SetParameter(new Parameter("id", model.Id, ParameterType.UrlSegment));

                    SetBody(model);

                    var response = SendRequest(Method.PUT, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);

                }
                else
                {
                    SetBody(model);

                    var response = SendRequest(Method.POST, EndPoint, Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Select()
        {
            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<List<Office>>(response.Content);

            return PartialView(model);
        }
    }
}

tuconciergeweb/Controllers/StaffController.cs
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tuconciergemodels;
using tuconciergeweb.Interfaces;
using tuconciergeweb.Services;

namespace tuconciergeweb.Controllers
{
    public class StaffController : BaseController
    {

        private readonly string EndPoint = "api/Staffs";

        public StaffController() : base() { }

        public ActionResult ConfirmDelete(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<StaffViewModel>(response.Content);

            return PartialView(model);
        }

        public JsonResult Delete(long id)
        {
            try
            {
                SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

                var response = SendRequest(Method.DELETE, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                return ValidateResponse(response);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Details(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<StaffViewModel>(response.Content);

            return PartialView(model);
        }

        public ActionResult Form(long id = 0)
        {
            if (id == 0)
            {
                ViewBag.ModalTitle = "Agregar personal";
                ViewBag.SaveTextButton = "Guardar";
                return PartialView(new StaffViewModel());
            }

            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<StaffViewModel>(response.Content);

            ViewBag.ModalTitle = "Editar personal";
            ViewBag.SaveTextButton = "Actualizar";
            return PartialView(model);
        }

        // GET: Staff
        public ActionResult Index()
        {
            if (!SessionActive())
            {
                return Redirect("/Home/Login");
            }

            return View();
        }

        public ActionResult List()
        {
            Enums.ModelStatus status = Enums.ModelStatus.Active;
            if (Request.QueryString["Status"] != null)
            {
                status = (Enums.ModelStatus)int.Parse(Request.QueryString["Status"].ToString());
            }

            SetParameter(new Parameter("Status", status, ParameterType.QueryString));

            if (Request.QueryString["Name"] != null)
            {
                var name = Request.QueryString["Name"].ToString();

                SetParameter(new Parameter("Name", name, ParameterType.QueryString));
            }

            if (Request.QueryString["FatherLastName"] != null)
            {
                var fatherLastName = Request.QueryString["FatherLastName"].ToString();

                SetParameter(new Parameter("FatherLastName", fatherLastName, ParameterType.QueryString));
            }

            if (Request.QueryString["OfficeId"] != null)
            {
                var OfficeId = Request.QueryString["OfficeId"].ToString();

                SetParameter(new Parameter("OfficeId", OfficeId, ParameterType.QueryString));
            }

            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<IEnumerable<StaffViewModel>>(response.Content);

            return PartialView(model);
        }

        public JsonResult Save(HttpPostedFileBase file, Staff model)
        {
            try
            {
                if (file != null)
                {
                    var fileUpload = new FileUploadService();

                    model.Photo = fileUpload.ImageUpload(file);
                }

                if (model.Id != 0)
                {
                    SetParameter(new Parameter("id", model.Id, ParameterType.UrlSegment));

                    SetBody(model);

                    var response = SendRequest(Method.PUT, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);

                }
                else
                {
                    SetBody(model);

                    var response = SendRequest(Method.POST, EndPoint, Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Select()
        {
            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<List<Staff>>(response.Content);

            return PartialView(model);
        }
    }
}

tuconciergeweb/Controllers/StatesController.cs
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tuconciergemodels;
using tuconciergeweb.Interfaces;

namespace tuconciergeweb.Controllers
{
    public class StatesController : BaseController, IViewController<State>
    {
        private readonly string EndPoint = "/api/States";

        public StatesController() : base() { }

        public ActionResult ConfirmDelete(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<StateViewModel>(response.Content);

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            try
            {
                SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

                var response = SendRequest(Method.DELETE, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                return ValidateResponse(response);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Details(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<StateViewModel>(response.Content);

            return PartialView(model);
        }

        public ActionResult Form(long id = 0)
        {
            if(id == 0)
            {
                ViewBag.ModalTitle = "Agrega estado";
                ViewBag.SaveTextButton = "Guardar";
                return PartialView(new StateViewModel());
            }

            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<StateViewModel>(response.Content);

            ViewBag.ModalTitle = "Editar estado";
            ViewBag.SaveTextButton = "Actualizar";
            return PartialView(model);
        }

        public ActionResult Index()
        {
            if (!SessionActive())
            {
                return Redirect("/Home/Login");
            }

            return View();
        }

        public ActionResult List()
        {
            Enums.ModelStatus status = Enums.ModelStatus.Active;
            if (Request.QueryString["Status"] != null)
            {
                status = (Enums.ModelStatus)int.Parse(Request.QueryString["Status"].ToString());
            }

            SetParameter(new Parameter("Status", status, ParameterType.QueryString));

            if (Request.QueryString["Name"] != null)
            {
                var name = Request.QueryString["Name"].ToString();

                SetParameter(new Parameter("Name", name, ParameterType.QueryString));
            }

            if (Request.QueryString["CountryId"] != null)
            {
                var countryId = int.Parse(Request.QueryString["CountryId"].ToString());

                SetParameter(new Parameter("CountryId", countryId, ParameterType.QueryString));
            }

            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<IEnumerable<StateViewModel>>(response.Content);

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Save(State model)
        {
            try
            {
                if (model.Id != 0)
                {
                    SetParameter(new Parameter("id", model.Id, ParameterType.UrlSegment));

                    SetBody(model);

                    var response = SendRequest(Method.PUT, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);

                }
                else
                {
                    SetBody(model);

                    var response = SendRequest(Method.POST, EndPoint, Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Select(long CountryId)
        {
            SetParameter(new Parameter("CountryId", CountryId, ParameterType.QueryString));

            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<List<StateViewModel>>(response.Content);

            return PartialView(model);
        }
    }
}

tuconciergeweb/Controllers/TypeAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tuconciergeweb.Controllers
{
    public class TypeAccountController : Controller
    {
        public ActionResult root()
        {
            return PartialView();
        }

        public ActionResult admin()
        {
            return PartialView();
        }

        public ActionResult responsable()
        {
            return PartialView();
        }
    }
}

tuconciergeweb/Views/TypeAccount/admin.cshtml
    <ul class="nav page-navigation">
        <li class="nav-item" id="navHome">
            <a class="nav-link" href="@Url.Action("Index", "Home")">
                <i class="mdi mdi-hexagon-outline menu-icon"></i>
                <span class="menu-title">Inicio</span>
            </a>
        </li>
        <li class="nav-item" id="navOffices">
            <a class="nav-link" href="@Url.Action("Index", "Offices")">
                <i class="mdi mdi-map-marker-circle menu-icon"></i>
                <span class="menu-title">Sucursales</span>
            </a>
        </li>
        <li class="nav-item" id="navCoverages">
            <a class="nav-link" href="@Url.Action("Index", "Coverages")">
                <i class="ion ion-md-globe menu-icon"></i>
                <span class="menu-title">Coverturas</span>
            </a>
        </li>
        <li class="nav-item" id="navCompanies">
            <a class="nav-link" href="@Url.Action("Index", "Services")">
                <i class="ion ion-md-star-outline menu-icon"></i>
                <span class="menu-title">Servicios</span>
            </a>
        </li>
        <li class="nav-item" id="navContracts">
            <a href="@Url.Action("Index", "Contracts")" class="nav-link">
                <i class="mdi mdi-clipboard-outline menu-icon"></i>
                <span class="menu-title">Contratos</span>
                <i class="menu-arrow"></i>
            </a>
            <!--<div class="submenu">
                <ul class="submenu-item">
                    <li class="nav-item" id="navCountries"><a class="nav-link" href="@Url.Action("Index", "Countries")">Gestión de contratos</a></li>
                    <li class="nav-item" id="navStates"><a class="nav-link" href="@Url.Action("Index", "States")">Gestión de cobro</a></li>
                    <li class="nav-item" id="navStates"><a class="nav-link" href="@Url.Action("Index", "States")">Historial de contratos</a></li>
                </ul>
            </div>-->
        </li>
        <li class="nav-item" id="navStaff">
            <a class="nav-link" href="@Url.Action("Index", "Staff")">
                <i class="mdi mdi-face menu-icon"></i>
                <span class="menu-title">Personal</span>
            </a>
        </li>
        <!--<li class="nav-item mega-menu">
        <a href="#" class="nav-link">
            <i class="ion ion-md-apps menu-icon"></i>
            <span class="menu-title">Recursos Humanos</span>
            <i class="menu-arrow"></i>
        </a>
        <div class="submenu">
            <div class="col-group-wrapper row">
                <div class="col-group col-md-4">
                    <div class="row">
                        <div class="col-12">
                            <p class="category-heading">Basic Elements</p>
                            <div class="submenu-item">
                                <div class="row">
                                    <div class="col-md-6">
                                        <ul>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/accordions.html">Accordion</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/buttons.html">Buttons</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/badges.html">Badges</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/breadcrumbs.html">Breadcrumbs</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/dropdowns.html">Dropdown</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/modals.html">Modals</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-6">
                                        <ul>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/progress.html">Progress bar</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/pagination.html">Pagination</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/tabs.html">Tabs</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/typography.html">Typography</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/tooltips.html">Tooltip</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-group col-md-4">
                    <div class="row">
                        <div class="col-12">
                            <p class="category-heading">Advanced Elements</p>
                            <div class="submenu-item">
                                <div class="row">
                                    <div class="col-md-6">
                                        <ul>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/dragula.html">Dragula</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/carousel.html">Carousel</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/clipboard.html">Clipboard</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/context-menu.html">Context Menu</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/loaders.html">Loader</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/slider.html">Slider</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-6">
                                        <ul>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/popups.html">Popup</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/notifications.html">Notification</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-group col-md-4">
                    <p class="category-heading">Icons</p>
                    <ul class="submenu-item">
                        <li class="nav-item"><a class="nav-link" href="pages/icons/flag-icons.html">Flag Icons</a></li>
                        <li class="nav-item"> <a class="nav-link" href="pages/icons/mdi.html">Mdi icons</a></li>
                        <li class="nav-item"><a class="nav-link" href="pages/icons/font-awesome.html">Font Awesome</a></li>
                        <li class="nav-item"><a class="nav-link" href="pages/icons/simple-line-icon.html">Simple Line Icons</a></li>
                        <li class="nav-item"><a class="nav-link" href="pages/icons/themify.html">Themify Icons</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </li>-->
    </ul>

tuconciergeweb/Views/TypeAccount/responsable.cshtml
<ul class="nav page-navigation">
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "Home")">
            <i class="ion ion-md-home menu-icon"></i>
            <span class="menu-title">Inicio</span>
        </a>
    </li>
    <!--
    <li class="nav-item">
        <a href="#" class="nav-link">
            <i class="ion ion-md-document menu-icon"></i>
            <span class="menu-title">Catálogos</span>
            <i class="menu-arrow"></i>
        </a>
        <div class="submenu">
            <ul class="submenu-item">
                <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Countries")"></a></li>
                <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "States")">Estados</a></li>
                <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Companies")">Empresas</a></li>
                <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "TypeServices")">Tipos de Servicios</a></li>
                <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Services")">Servicios</a></li>
            </ul>
        </div>
    </li>-->
    <li class="nav-item mega-menu">
        <a href="#" class="nav-link">
            <i class="ion ion-md-apps menu-icon"></i>
            <span class="menu-title">Recursos Humanos</span>
            <i class="menu-arrow"></i>
        </a>
        <div class="submenu">
            <div class="col-group-wrapper row">
                <div class="col-group col-md-4">
                    <div class="row">
                        <div class="col-12">
                            <p class="category-heading">Basic Elements</p>
                            <div class="submenu-item">
                                <div class="row">
                                    <div class="col-md-6">
                                        <ul>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/accordions.html">Accordion</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/buttons.html">Buttons</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/badges.html">Badges</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/breadcrumbs.html">Breadcrumbs</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/dropdowns.html">Dropdown</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/modals.html">Modals</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-6">
                                        <ul>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/progress.html">Progress bar</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/pagination.html">Pagination</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/tabs.html">Tabs</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/typography.html">Typography</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/tooltips.html">Tooltip</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-group col-md-4">
                    <div class="row">
                        <div class="col-12">
                            <p class="category-heading">Advanced Elements</p>
                            <div class="submenu-item">
                                <div class="row">
                                    <div class="col-md-6">
                                        <ul>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/dragula.html">Dragula</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/carousel.html">Carousel</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/clipboard.html">Clipboard</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/context-menu.html">Context Menu</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/loaders.html">Loader</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/slider.html">Slider</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-6">
                                        <ul>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/popups.html">Popup</a></li>
                                            <li class="nav-item"><a class="nav-link" href="pages/ui-features/notifications.html">Notification</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-group col-md-4">
                    <p class="category-heading">Icons</p>
                    <ul class="submenu-item">
                        <li class="nav-item"><a class="nav-link" href="pages/icons/flag-icons.html">Flag Icons</a></li>
                        <li class="nav-item"> <a class="nav-link" href="pages/icons/mdi.html">Mdi icons</a></li>
                        <li class="nav-item"><a class="nav-link" href="pages/icons/font-awesome.html">Font Awesome</a></li>
                        <li class="nav-item"><a class="nav-link" href="pages/icons/simple-line-icon.html">Simple Line Icons</a></li>
                        <li class="nav-item"><a class="nav-link" href="pages/icons/themify.html">Themify Icons</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </li>
</ul>