tuconciergeweb/Controllers/OfficesController.cs
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tuconciergemodels;
using tuconciergeweb.Interfaces;
using tuconciergeweb.Services;

namespace tuconciergeweb.Controllers
{
    public class OfficesController : BaseController
    {
        private readonly string EndPoint = "/api/Offices";

        // CONSTRUCTOR
        public OfficesController() : base() { }

        public ActionResult ConfirmDelete(long id)
        {
            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<OfficeViewModel>(response.Content);

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            try
            {
                SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

                var response = SendRequest(Method.DELETE, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                return ValidateResponse(response);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Details(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<OfficeViewModel>(response.Content);

            return PartialView(model);
        }

        public ActionResult Location(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<OfficeViewModel>(response.Content);

            ViewBag.ModalTitle = "Establecer ubicación";
            ViewBag.SaveTextButton = "Guardar";
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult SaveLocation(Office model)
        {
            SetParameter(new Parameter("id", model.Id, ParameterType.UrlSegment));

            SetBody(model);

            var response = SendRequest(Method.PUT, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            return ValidateResponse(response);
        }

        public ActionResult Form(long id = 0)
        {
            if (id == 0)
            {
                ViewBag.ModalTitle = "Agregar sucursal";
                ViewBag.SaveTextButton = "Guardar";
                return PartialView(new OfficeViewModel());
            }

            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<OfficeViewModel>(response.Content);

            ViewBag.ModalTitle = "Editar sucursal";
            ViewBag.SaveTextButton = "Actualizar";
            return PartialView(model);
        }


        // GET: Countries
        public ActionResult Index()
        {
            if (!SessionActive())
            {
                return Redirect("/Home/Login");
            }

            return View();
        }

        public ActionResult List()
        {
            if (Request.QueryString["Name"] != null)
            {
                var name = Request.QueryString["Name"].ToString();

                SetParameter(new Parameter("Name", name, ParameterType.QueryString));
            }

            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<IEnumerable<OfficeViewModel>>(response.Content);

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Save(HttpPostedFileBase file, Office model)
        {
            try
            {
                if(file != null)
                {
                    var fileUpload = new FileUploadService();

                    model.Picture = fileUpload.ImageUpload(file);
                }

                if (model.Id != 0)
                {
                    SetParameter(new Parameter("id", model.Id, ParameterType.UrlSegment));

                    SetBody(model);

                    var response = SendRequest(Method.PUT, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);

                }
                else
                {
                    SetBody(model);

                    var response = SendRequest(Method.POST, EndPoint, Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Select()
        {
            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<List<Office>>(response.Content);

            return PartialView(model);
        }
    }
}

tuconciergeweb/Controllers/ServicesController.cs
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tuconciergemodels;
using tuconciergeweb.Interfaces;

namespace tuconciergeweb.Controllers
{
    public class ServicesController : BaseController, IViewController<Service>
    {
        private readonly string EndPoint = "/api/Services";

        public ServicesController() : base() { }

        public ActionResult ConfirmDelete(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<ServiceViewModel>(response.Content);

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            try
            {
                SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

                var response = SendRequest(Method.DELETE, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                return ValidateResponse(response);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Details(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<ServiceViewModel>(response.Content);

            return PartialView(model);
        }

        public ActionResult Form(long id = 0)
        {
            if (id == 0)
            {
                ViewBag.ModalTitle = "Agregar servicio";
                ViewBag.SaveTextButton = "Guardar";
                return PartialView(new ServiceViewModel());
            }

            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<ServiceViewModel>(response.Content);

            ViewBag.ModalTitle = "Editar servicio";
            ViewBag.SaveTextButton = "Actualizar";
            return PartialView(model);
        }

        // GET: Services
        public ActionResult Index()
        {
            if (!SessionActive())
            {
                return Redirect("/Home/Login");
            }

            return View();
        }

        public ActionResult List()
        {
            Enums.ModelStatus status = Enums.ModelStatus.Active;
            if (Request.QueryString["Status"] != null)
            {
                status = (Enums.ModelStatus)int.Parse(Request.QueryString["Status"].ToString());
            }

            SetParameter(new Parameter("Status", status, ParameterType.QueryString));

            if (Request.QueryString["Name"] != null)
            {
                var name = Request.QueryString["Name"].ToString();

                SetParameter(new Parameter("Name", name, ParameterType.QueryString));
            }

            if (Request.QueryString["TypeServiceId"] != null)
            {
                var TypeServiceId = int.Parse(Request.QueryString["TypeServiceId"].ToString());

                SetParameter(new Parameter("TypeServiceId", TypeServiceId, ParameterType.QueryString));
            }

            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<IEnumerable<ServiceViewModel>>(response.Content);

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Save(Service model)
        {
            try
            {
                if (model.Id != 0)
                {
                    SetParameter(new Parameter("id", model.Id, ParameterType.UrlSegment));

                    SetBody(model);

                    var response = SendRequest(Method.PUT, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);

                }
                else
                {
                    SetBody(model);

                    var response = SendRequest(Method.POST, EndPoint, Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

tuconciergeweb/Controllers/TypeServicesController.cs
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tuconciergemodels;
using tuconciergeweb.Interfaces;
using tuconciergeweb.Services;

namespace tuconciergeweb.Controllers
{
    public class TypeServicesController : BaseController
    {
        private readonly string EndPoint = "/api/TypeServices";

        public TypeServicesController() : base() { }

        public ActionResult ConfirmDelete(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<TypeService>(response.Content);

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            try
            {
                SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

                var response = SendRequest(Method.DELETE, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                return ValidateResponse(response);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Details(long id)
        {
            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<TypeService>(response.Content);

            return PartialView(model);
        }

        public ActionResult Form(long id = 0)
        {
            if (id == 0)
            {
                ViewBag.ModalTitle = "Agrega tipo de servicio";
                ViewBag.SaveTextButton = "Guardar";
                return PartialView(new TypeService());
            }

            SetParameter(new Parameter("id", id, ParameterType.UrlSegment));

            var response = SendRequest(Method.GET, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<TypeService>(response.Content);

            ViewBag.ModalTitle = "Editar tipo de servicio";
            ViewBag.SaveTextButton = "Actualizar";
            return PartialView(model);
        }

        // GET: TypeServices
        public ActionResult Index()
        {
            if (!SessionActive())
            {
                return Redirect("/Home/Login");
            }

            return View();
        }

        public ActionResult List()
        {
            Enums.ModelStatus status = Enums.ModelStatus.Active;
            if (Request.QueryString["Status"] != null)
            {
                status = (Enums.ModelStatus)int.Parse(Request.QueryString["Status"].ToString());
            }

            SetParameter(new Parameter("Status", status, ParameterType.QueryString));

            if (Request.QueryString["Name"] != null)
            {
                var name = Request.QueryString["Name"].ToString();

                SetParameter(new Parameter("Name", name, ParameterType.QueryString));
            }

            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<IEnumerable<TypeService>>(response.Content);

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Save(HttpPostedFileBase file, TypeService model)
        {
            try
            {
                if (file != null)
                {
                    var fileUpload = new FileUploadService();

                    model.Image = fileUpload.ImageUpload(file);
                }

                if (model.Id != 0)
                {
                    SetParameter(new Parameter("id", model.Id, ParameterType.UrlSegment));

                    SetBody(model);

                    var response = SendRequest(Method.PUT, EndPoint + "/{id}", Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);

                }
                else
                {
                    SetBody(model);

                    var response = SendRequest(Method.POST, EndPoint, Enums.Authentication.DEFAULT);

                    return ValidateResponse(response);
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errors = ex }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Select()
        {
            var response = SendRequest(Method.GET, EndPoint, Enums.Authentication.DEFAULT);

            var model = JsonConvert.DeserializeObject<List<TypeService>>(response.Content);

            return PartialView(model);
        }
    }
}

tuconciergeweb/Views/Services/ConfirmDelete.cshtml
@model tuconciergemodels.ServiceViewModel

<div class="modal-header">
    <h5 class="modal-title" id="smModalLabel">¿Estás seguro que quieres eliminar esto?</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i class="ion ion-md-close-circle-outline"></i>
    </button>
</div>
<div class="modal-body" id="mdModalBody">

    <dl>

        <dt>
            Servicio
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Tipo de servicio
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeService.Name)
        </dd>

    </dl>

</div>
<div class="modal-footer">
    <button id="btnCancel" type="button" class="btn btn-danger btn-rounded btn-fw" data-dismiss="modal">Cancelar</button>
    <button id="btnDelete" type="button" class="btn btn-success btn-rounded btn-fw" onclick="Delete(@Model.Id);">Sí, eliminar</button>
</div>

tuconciergeweb/Views/Services/Details.cshtml
@model tuconciergemodels.ServiceViewModel

<div class="modal-header">
    <h5 class="modal-title" id="smModalLabel">Información del servicio</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i class="ion ion-md-close-circle-outline"></i>
    </button>
</div>
<div class="modal-body" id="mdModalBody">

    <dl>

        <dt>
            Servicio
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Descripción
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        
        <dt>
            Recordarios
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Recordatorios)
        </dd>

        <dt>
            Tipo de servicio
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeService.Name)
        </dd>
        
        <dt>
            Sucursal
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Office.Name)
        </dd>

        <dt>
            Fecha de registro
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>
    </dl>

</div>
<div class="modal-footer">
    <button id="btnCancel" type="button" class="btn btn-dark btn-rounded btn-fw" data-dismiss="modal">Cancelar</button>
</div>

tuconciergeweb/Views/Services/Form.cshtml
@model tuconciergemodels.ServiceViewModel

<div class="modal-header">
    <h5 class="modal-title">@ViewBag.ModalTitle</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i class="ion ion-md-close-circle-outline"></i>
    </button>
</div>
<div class="modal-body" id="mdModalBody">

    <form id="serviceForm">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label for="Name">Nombre</label>
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nombre" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="Description">Descripción</label>
            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @placeholder = "Descripción" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
        
        <div class="form-group">
            <label for="Recordatorios">Recordatorios</label>
            @Html.TextAreaFor(model => model.Recordatorios, new { @class = "form-control", @placeholder = "Recordarios" })
            @Html.ValidationMessageFor(model => model.Recordatorios, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="selectTypeService">Tipo de servicio</label>
            <select class="form-control" id="selectTypeService">
                <option value="0">Seleccionar...</option>
                @Html.Action("Select", "TypeServices")
            </select>
        </div>
        
        <div class="form-group">
            <label for="selectOffice">Sucursal</label>
            <select class="form-control" id="selectOffice">
                <option value="0">Seleccionar...</option>
                @Html.Action("Select", "Offices")
            </select>
        </div>

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.TypeServiceId)
        @Html.HiddenFor(model => model.IdOffice)

    </form>

</div>
<div class="modal-footer">
    <button id="btnCancel" type="button" class="btn btn-danger btn-rounded btn-fw" data-dismiss="modal">Cancelar</button>
    <button id="btnSave" type="button" class="btn btn-success btn-rounded btn-fw" onclick="Save();">@ViewBag.SaveTextButton</button>
</div>

tuconciergeweb/Views/Services/Index.cshtml
@{
    ViewBag.Title = "Servicios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                Catálogo servicios
            </h4>
            <div class="row d-flex align-items-center justify-content-start">

                <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                    <div class="form-group">
                        <label for="NameFilter">Nombre</label>
                        <input type="text" class="form-control" id="NameFilter" placeholder="Nombre">
                    </div>
                </div>

                <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                    <div class="form-group">
                        <label for="selectTypeServiceFilter">Tipo de servicio</label>
                        <select class="form-control" id="selectTypeServiceFilter">
                            <option value="0">Seleccionar...</option>
                            @Html.Action("Select", "TypeServices")
                        </select>
                    </div>
                </div>

                <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                    <button type="button" class="btn btn-dark btn-rounded btn-fw" onclick="getList();">Buscar</button>
                </div>

            </div>
            <div class="row">
                <div class="col-lg-12 mt-3 d-flex justify-content-end">
                    <button type="button" class="btn btn-success btn-rounded btn-fw" onclick="Create();">Agregar</button>
                </div>
                <div class="col-lg-12 mt-3">
                    <div class="table-responsive" id="MyTable">

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@section scripts {
    <script src="~/Scripts/Services.js"></script>
    <script src="~/Scripts/SalesPlan.js"></script>
    <script src="~/Scripts/Complements.js"></script>
}

tuconciergeweb/Views/Services/List.cshtml
@model IEnumerable<tuconciergemodels.ServiceViewModel>
@{
    ViewBag.CountElements = 0;
}

    <table class="table table-hover">
        <thead>
            <tr>
                <th>No.</th>
                <th>Servicio</th>
                <th>Tipo de Servicio</th>
                <th>Sucursales</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() > 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @(ViewBag.CountElements += 1)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TypeService.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Office.Name)
                        </td>
                        <td>
                            
                            <button type="button" class="btn btn-info btn-rounded btn-icon" onclick="getPlans(@item.Id);">
                                <i class="mdi mdi-folder"></i>
                            </button> |
                            <button type="button" class="btn btn-info btn-rounded btn-icon" onclick="Details(@item.Id)">
                                <i class="ion ion-md-eye"></i>
                            </button> |
                            <button type="button" class="btn btn-warning btn-rounded btn-icon" onclick="Edit(@item.Id);">
                                <i class="ion ion-md-refresh"></i>
                            </button> |
                            <button type="button" class="btn btn-danger btn-rounded btn-icon" onclick="ConfirmDelete(@item.Id);">
                                <i class="ion ion-md-trash"></i>
                            </button>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="6" align="center">
                        <h5>Sin resultados</h5>
                    </td>
                </tr>
            }
        </tbody>
    </table>